### ISSUE TITLE
models.py is not in your repository.

### ISSUE THREAD

**Issue by Martin1007Wang** [zhangdddong/SimRE#2]
from models import build_model, ModelOutput, RuleEmbedding, RuleModelOutput
Traceback (most recent call last):
  File "src/main.py", line 6, in <module>
    from trainer import Trainer, RuleTrainer
  File "SimRE/src/trainer.py", line 19, in <module>
    from models import build_model, ModelOutput, RuleEmbedding, RuleModelOutput
ModuleNotFoundError: No module named 'models'

**Comment by hxj2802** [comment]
hello，I have the same question,have you solved it yet?

**Comment by Martin1007Wang** [comment]
> hello，I have the same question,have you solved it yet?

No. The author's code repository appears to be incomplete, and as such, there seems to be no immediate need for further follow-up research based on the current paper.

**Comment by hxj2802** [comment]
got it,thank you
